# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-18 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
